### ISSUE TITLE
Missing License, please supply a license. (Neat+1.7-23.jar)

### ISSUE THREAD

**Issue by matt-dolio** [Vazkii/Neat#62]
There is a closed ticket from a few days ago saying they incorrectly thought the mod was updated to 1.16.3, but on CurseForge it clearly states it is 1.16.X compatible. Is a fix coming soon, or is the mod actually not updated for 1.16.X yet? If so, the publicly accessible files and tags that claim compatibility should be removed until it actually is.

**Comment by xMGZx** [comment]
I'm pretty sure that the only thing needed to fix this is adding the line
`license="Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License"`
to the [mods.toml](https://github.com/Vazkii/Neat/blob/master/src/main/resources/META-INF/mods.toml) file underneath the `issueTrackerURL` line.

Did this inside of the .jar file (you can rename it to a .zip file if you don't have something like 7-zip) and it worked fine in 1.16.3. Though perhaps there's some bug that I haven't discovered yet since 1.16.3 did change a few things
